/**
 * POST /api/contracts/create
 *
 * Triggered by the Airtable automation when a new contract form is submitted.
 *
 * Expected JSON body:
 * {
 *   contractId: string,          // unique id, generated by Airtable automation
 *   signers: Array<{
 *     name: string,
 *     email: string,
 *     cpf?: string
 *   }>
 * }
 *
 * Steps:
 *   1. Download the contract template PDF from Google Drive
 *   2. Store a new contract record in Airtable with status "pending"
 *   3. Call /api/contracts/sign internally (same process, direct import)
 */

import type { VercelRequest, VercelResponse } from "@vercel/node";
import { fetchTemplateBuffer } from "../lib/gdrive";
import { createContractRecord } from "../lib/airtable";
import { processSignature } from "./sign";

interface CreateBody {
  contractId: string;
  signers: Array<{ name: string; email: string; cpf?: string }>;
}

function validateBody(body: unknown): body is CreateBody {
  if (!body || typeof body !== "object") return false;
  const b = body as Record<string, unknown>;
  if (typeof b.contractId !== "string" || !b.contractId.trim()) return false;
  if (!Array.isArray(b.signers) || b.signers.length === 0) return false;
  for (const s of b.signers) {
    if (!s || typeof s !== "object") return false;
    const signer = s as Record<string, unknown>;
    if (typeof signer.name !== "string" || !signer.name.trim()) return false;
    if (typeof signer.email !== "string" || !signer.email.includes("@")) return false;
  }
  return true;
}

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
): Promise<void> {
  if (req.method !== "POST") {
    res.status(405).json({ error: "Method not allowed" });
    return;
  }

  if (!validateBody(req.body)) {
    res.status(400).json({
      error: "Invalid body. Required: { contractId: string, signers: [{ name, email }] }",
    });
    return;
  }

  const { contractId, signers } = req.body;

  try {
    // 1. Download template from Google Drive as PDF
    const pdfBuffer = await fetchTemplateBuffer();
    const pdfBase64 = pdfBuffer.toString("base64");

    // 2. Create Airtable record
    const airtableRecordId = await createContractRecord({
      contractId,
      status: "pending",
      signers: JSON.stringify(signers.map((s) => ({ ...s, signed: false }))),
    });

    // 3. Trigger signature flow (gov.br or fallback)
    await processSignature({ contractId, airtableRecordId, pdfBase64, signers });

    res.status(202).json({
      ok: true,
      contractId,
      airtableRecordId,
      message: "Contract created and signature process initiated.",
    });
  } catch (err) {
    console.error("[create] error:", err);
    res.status(500).json({
      error: err instanceof Error ? err.message : "Internal server error",
    });
  }
}
